# path = "/Users/brianzhong/DropBox/" #brian's path
path <- "~/Dropbox/" #seth's path
# F_2010 <- read_excel(paste0(path,"Behavioural Data for Seth/2014_groupHH_FOCALdata.xlsx"), sheet = "alldata_randomised")
# F_2012_novigilance <- read_excel(paste0(path,"Behavioural Data for Seth/2012_GroupF_Masterdatafile.xls", sheet = "behaviours_no vigilance")
# F_2011 <- read_excel(paste0(path,"Behavioural Data for Seth/Group F_FOCAL DATA MASTERCOPY_2011.xlsx"), sheet = "DATA")
# S_2011 <- read_excel(paste0(path,"Behavioural Data for Seth/Group S FOCAL DATA Sam Larson 2011", sheet = "DATA no Duplicate DAYS")
HH_2014 <- read_excel(paste0(path,"Behavioural Data for Seth/2014_groupHH_FOCALdata.xlsx"), sheet = "2014 HH FOCAL")
KK_2015 <- read_excel(paste0(path,"Behavioural Data for Seth/2015_groupKK_FOCALdata.xlsx"), sheet = "grpKK_2015")
V_2015 <- read_excel(paste0(path,"Behavioural Data for Seth/2015_GroupV_FOCALdata.xlsx"), sheet = "groupV 2015")
R_2015 <- read_excel(paste0(path,"Behavioural Data for Seth/2015.GroupR_focal_MASTERFILE.xlsx"), sheet = "DATA")
V_2016 <- read_excel(paste0(path,"Behavioural Data for Seth/2016_GroupV_MASTERFILE.xlsx"), sheet = "Sheet1")
F_2016 <- read_excel(paste0(path,"Behavioural Data for Seth/2016.GrpF_Masterfile.xlsx"), sheet = "2016.GrpF_MASTER")
F_2015 <- read_excel(paste0(path,"Behavioural Data for Seth/GroupF_2015_FOCALdata.xlsx"), sheet = "behaviours")
F_2013 <- read_excel(paste0(path,"Behavioural Data for Seth/GrpF focal data_2013 MASTERFILE.xls"), sheet = "behaviours")
F_2014 <- read_excel(paste0(path,"Behavioural Data for Seth/Masterdatafile2014_ALL_GroupF.xls"), sheet = "behaviours")
oxtr_genotypes <- read_excel(paste0(path,"Behavioural Data for Seth/genotypes.xlsx"), sheet = "OXTR")
avpr1a_genotypes <- read_excel(paste0(path,"Behavioural Data for Seth/genotypes.xlsx"), sheet = "AVPR1A")
avpr1b_genotypes <- read_excel(paste0(path,"Behavioural Data for Seth/genotypes.xlsx"), sheet = "AVPR1B")
tph1_genotypes <- read_excel(paste0(path,"Behavioural Data for Seth/genotypes.xlsx"), sheet = "TPH1")
tph2_genotypes <- read_excel(paste0(path,"Behavioural Data for Seth/genotypes.xlsx"), sheet = "TPH2")
pedigree <- read_excel(paste0(path,"Pedigree and Life-History Data/PEDIGREE_updated2016.xlsx"), sheet = "Demographic Data")
pedigree <- as.data.table(pedigree)
dominance <- read_excel(paste0(path,"Subjects_attributes, dominance, etc/Dominance Hierarchies/DOMINANCE_ALLSUBJECTS_LONGLIST.xlsx"), sheet = "DOMINANCE_ALLSUBJECTS")

