library(readxl)

HH_2014 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/HH_2014.xlsx", sheet = "2014 HH FOCAL")
# F_2010 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2010.xlsx", sheet = "alldata_randomised")
# F_2012_novigilance <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2012.xls", sheet = "behaviours_no vigilance")
KK_2015 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/KK_2015.xlsx", sheet = "grpKK_2015")
V_2015 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/V_2015.xlsx", sheet = "groupV 2015")
R_2015 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/R_2015.xlsx", sheet = "DATA")
V_2016 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/V_2016.xlsx", sheet = "Sheet1")
F_2016 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2016.xlsx", sheet = "2016.GrpF_MASTER")
# F_2011 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2011.xlsx", sheet = "DATA")
# S_2011 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/S_2011.xlsx", sheet = "DATA no Duplicate DAYS")
F_2015 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2015.xlsx", sheet = "behaviours")
F_2013 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2013.xls", sheet = "behaviours")
F_2014 <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/F_2014.xls", sheet = "behaviours")
oxtr_genotypes <- read_excel("/Users/brianzhong/Desktop/Genomic Data/oxtr_genotypes.xlsx", sheet = "Sheet1")
avpr1a_genotypes <- read_excel("/Users/brianzhong/Desktop/Genomic Data/avpr1a_genotypes.xlsx", sheet = "Sheet1")
avpr1b_genotypes <- read_excel("/Users/brianzhong/Desktop/Genomic Data/avpr1b_genotypes.xlsx", sheet = "Sheet1")
tph1_genotypes <- read_excel("/Users/brianzhong/Desktop/Genomic Data/tph1_genotypes.xlsx", sheet = "Sheet1")
tph2_genotypes <- read_excel("/Users/brianzhong/Desktop/Genomic Data/tph2_genotypes.xlsx", sheet = "Sheet1")
pedigree <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/PEDIGREE_updated2016.xlsx", sheet = "Demographic Data")
dominance <- read_excel("/Users/brianzhong/Desktop/Behavioral Data/DOMINANCE_ALLSUBJECTS_LONGLIST.xlsx", sheet = "DOMINANCE_ALLSUBJECTS")
oxtr_r2 <- read_excel("/Users/brianzhong/Desktop/Genomic Data/r2 values.xlsx", sheet = "OXTR")
avpr1a_r2 <- read_excel("/Users/brianzhong/Desktop/Genomic Data/r2 values.xlsx", sheet = "AVPR1A")
avpr1b_r2 <- read_excel("/Users/brianzhong/Desktop/Genomic Data/r2 values.xlsx", sheet = "AVPR1B")
